#define COMBO_KEY_BUFFER_LENGTH 6
#define COMBO_BUFFER_LENGTH 4
#define COMBO_TERM 40

#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 1000

#define MK_3_SPEED
#define MK_C_INTERVAL_UNMOD 2
#define MK_C_OFFSET_UNMOD 128
